version: '3.8'

services:
 frontend:
    build:
      context: ./TP1-Cacace-Sofi-Frontend
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

 backend:
    build:
      context: ./TP1-Cacace-Sofi-Backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - MYSQLDATABASE= libros
      - MYSQLUSER= alumno
      - MYSQLPASSWORD= alumnoipm
      - DBHOST= localhost
      - DBPORT= 3306
    restart: always   
    
 mysql:
    image: mysql:8
    restart: always
    container_name: db
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: alumnoipm
      MYSQL_DATABASE: libros
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumnoipm

networks:
  app-network:
    driver: bridge

